#dist: xenial
git:
  quiet: true
  depth: 1
notifications:
  email: false
language: java
jdk: openjdk8
#python: 3
#node_js: lts/*
install: true
env:
  global:
    - TERM=dumb
    - secure: yOuzuo2TQKTb7NLR0q3hxYQu0D5RTiV2L6k7JrteqCJgaAtL5Hb8FzT2euV1FM4K23/rz1Yh6FpHXrvYhtF19CP2SLIkrDpNy3ENDLu8b/PSWQOoU1GfFBHXP2VCe+uaIHaICPx/fNRquBMWHovZgWT5Kdtd0x8zrr1zkq3JK4kBwM/XswqaUp/M1jBP3DJCG3RldBth0Dw11rGDrOfDyMZp5+5X5Cp9Pu+2GHLlkZMsTRrfzfsa9cKPXNu0KaQuPilm+72STF2ULVTyw1QP+triUxj/fnnaVuewY6c1eqpOdvi+FxblLSBnKUYIKO4XcqDorlXhGWu1zyJbXKAQswrJ9kLjKW63Xfmnr6HDu2NaGf/9fnqg4z9Mr7zBL6jiHIMTSdhmotCR9XUxo+qFUdPsgDWlD8SUN5lieHphjGoaD2+UyNIwgqYF9Ry8ro56mBZ+T75lcfaEhwkcvvOjYfwhqW5MAN5o4Akgr08k/+Wd0R47fz9iyMb+qJBev1j83JMWWean3ejdr8vz+iuolX3ufY2tSKsk3upz0mUeMjmoxzAgwf7BY8TXeaXBsO2rgRLmJ+tQdYlalZsTuPKC5oSBkRTj4LRsMgp1dfUMiir6kxhjAfEVQSj4CZ36fnXfg7JjAesab0cQnhppoJHCR0ECfdePw2J2z5Y9cOOF2CE=
addons:
  apt:
    update: true
    packages:
      - jq
      - sudo
      - lsof
      - wget
      - bash
      - curl
#      - python3-dev
#      - python3-pip
#      - python3-six
#      - python3-setuptools
before_install:
#  - export PATH=$HOME/.local/bin:$PATH
#  - pip3 install --user $(whoami) --upgrade pip >/dev/null
#  - pip install --user $(whoami) --upgrade httpie >/dev/null 2>&1
#  - http --version --debug
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 5432 5672 27017 8080 8000 8081 80 80
jobs:
  include:
    - stage: openjdk8
      jdk: openjdk8
      name: tests
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/node_modules"
    - node_modules
    - "~/.gradle"
    - "~/.ivy"
    - "~/.sbt"
    - "~/.m2"
  pip: true
  npm: true
  packages: true
before_deploy:
  - cd $TRAVIS_BUILD_DIR && ./gradlew npm_i npm_run_gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ".vuepress/dist"
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
