/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details take a look at the Scala plugin chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/scala_plugin.html
 */
import org.gradle.api.tasks.testing.logging.TestLogEvent.*

plugins {
    // Apply the scala plugin to add support for Scala
    scala
    id("com.moowork.node") version "1.3.1"
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    val scalaVersion = "2.12"
    // Use Scala 2.12 in our library project
    implementation("org.scala-lang:scala-library:$scalaVersion.8")

    // Use Scalatest for testing our library
    testImplementation("junit:junit:4.12")
    testImplementation("org.scalatest:scalatest_$scalaVersion:3.0.5")

    // Need scala-xml at test runtime
    testRuntimeOnly("org.scala-lang.modules:scala-xml_$scalaVersion:1.1.1")
}

tasks {
    withType<Test> {
        testLogging {
            showExceptions = true
            showStandardStreams = true
            events(PASSED, SKIPPED, FAILED)
        }
    }
}

node {
    download = true
}

defaultTasks("clean", "build")
